// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXTmr77cEy6ET4k0JJ9NYlOxltEEu2CSk',
    appId: '1:1007800816348:web:4be9c62a5a7a5788f6da19',
    messagingSenderId: '1007800816348',
    projectId: 'greentruck-860d2',
    authDomain: 'greentruck-860d2.firebaseapp.com',
    storageBucket: 'greentruck-860d2.appspot.com',
    measurementId: 'G-EQX97ZBTS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIUInZfr5RVv3Lm_8DOK9gobmA2FKWPE',
    appId: '1:1007800816348:android:fe8640cf84380f03f6da19',
    messagingSenderId: '1007800816348',
    projectId: 'greentruck-860d2',
    storageBucket: 'greentruck-860d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-Xb6p9uUg5jQcpMf84We4aTODeS0GN4',
    appId: '1:1007800816348:ios:6186a43d93080f84f6da19',
    messagingSenderId: '1007800816348',
    projectId: 'greentruck-860d2',
    storageBucket: 'greentruck-860d2.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-Xb6p9uUg5jQcpMf84We4aTODeS0GN4',
    appId: '1:1007800816348:ios:6186a43d93080f84f6da19',
    messagingSenderId: '1007800816348',
    projectId: 'greentruck-860d2',
    storageBucket: 'greentruck-860d2.appspot.com',
    iosBundleId: 'com.example.groceryapp',
  );
}
